name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the sections below.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of the bug
      placeholder: Describe what happened...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Run command '...'
        2. With parameters '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide your environment details
      value: |
        - OS: [e.g., Windows 11, Ubuntu 22.04]
        - Python version: [e.g., 3.10]
        - PyTorch version: [e.g., 2.0]
        - CUDA version: [e.g., 11.8 or CPU]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Paste any error messages or stack traces
      render: shell

  - type: dropdown
    id: model
    attributes:
      label: Model Used
      description: Which model were you using?
      options:
        - pnn
        - pannet
        - drpnn
        - pannet_cbam
        - mspannet
        - panformer
        - panformer_lite
        - Not applicable
